GO_VERSION=1.17.5
CLI_VERSION=20.10.11
ALPINE_VERSION=3.15.0
GOLANGCI_LINT_VERSION=v1.27.0-alpine
LTAG_VERSION=v0.2.3

GOOS ?= $(shell go env GOOS)
BINARY_EXT=
ifeq ($(GOOS),windows)
	BINARY_EXT=.exe
endif
PLATFORM_BINARY?=docker-scan_$(GOOS)_amd64$(BINARY_EXT)
BINARY=docker-scan$(BINARY_EXT)
