#!/bin/sh

set -eu

go mod tidy -compat=1.17
DIFF=$(git status --porcelain -- go.mod go.sum)

if [ "$DIFF" ]; then
    echo
    echo "These files were changed:"
    echo
    echo "$DIFF"
    echo
    exit 1
else
    echo "go.mod is correct"
fi;
